---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - awscli
  - bash-completion
  - boot2docker
  - brotli
  - composer
  - coreutils
  - ctags
  - ddgr
  - diffutils
  - docker-compose
  - doxygen
  - emacs
  - fontconfig
  - git
  - git-extras
  - git-flow
  - glances
  - go
  - googler
  - gzip
  - haskell-stack
  - htop
  - hub
  - iperf
  - jq
  - mcrypt
  - nmap
  - node
  - nvm
  - pandoc
  - perl
  - php
  - phpunit
  - postresql
  - python3
  - restic
  - ruby
  - rust
  - sqlite
  - ssh-copy-id
  - task
  - taskd
  - timewarrior
  - tmux
  - vim
  - vv
  - wget
  - wrk
  - yarn
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - java
  - racket
  - xquartz

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  - eslint
  - gulp
  - js-beautify
  - tslint
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
